[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob:; font-src 'self' data: blob: https://fonts.gstatic.com https://fonts.googleapis.com 'unsafe-inline'; connect-src 'self' https://*.supabase.co https://*.supabase.in;"

[[redirects]]
  from = "/health"
  to = "/api/health"
  status = 200

# API routes
[[edge_functions]]
  path = "/api/*"
  function = "api-handler"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false